name: Python workflow continuos integration

on:
  workflow_dispatch:
  push:
    branches: [feature/*] # Only for tests
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  ci_workflow:
    permissions:
      security-events: write
    uses: gustavo-studies-devops/github-pipeline/.github/workflows/python-workflow-ci.yaml@develop
    with:
      environment: ${{ vars.ENVIRONMENT }}
    secrets: inherit